version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: -1
  - package-ecosystem: "npm"
    directory: "server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: -1
